"use client";

/**
 * Scene 1 — Field-response video collage.
 *
 * Background: short loops of PPE-clad response teams, cross-faded on a
 * fixed cadence. Each clip is treated to read as atmosphere rather than
 * literal b-roll: object-cover fill, a slight scale, desaturation, and a
 * cool blue tint tying it to the page's ink palette, with a dark vignette
 * underneath the headline for legibility.
 *
 * SELF-HOSTED CLIPS
 *   The clips are small, pre-trimmed, web-optimized MP4s served from
 *   `public/hero/`. They are generated by `npm run build:hero-clips`,
 *   which fetches each source once, cuts it to the window we show, and
 *   compresses it. Because each file IS the window (no seeking into a
 *   long remote file) playback starts instantly and loops natively — so
 *   this component carries none of the ranged-seek / EOF-wrap machinery
 *   the old remote-streaming version needed.
 *
 *   `poster.jpg` (also generated by that script) paints instantly, so the
 *   hero is never a black box while the first clip buffers. If the clips
 *   haven't been generated yet, the dark gradient backdrop shows through
 *   and the hero still reads as intentional.
 *
 * To change the collage, edit SOURCES in scripts/build-hero-clips.mjs
 * (the `id`s must match CLIPS below), then re-run the script.
 */

import { useEffect, useRef, useState } from "react";
import { useReducedMotion } from "@/lib/hooks";

type Clip = {
  id: string;
  description: string;
  /** File duration in seconds. Must match the trimmed window in
   *  scripts/build-hero-clips.mjs; if you re-trim, update here too.
   *  Used to schedule rotation BEFORE the native `loop` wraps to t=0
   *  — without this, short clips (≤ rotate cadence) visibly restart
   *  during their on-screen turn. */
  durationS: number;
};

// id → public/hero/<id>.mp4. Order is the rotation sequence.
const CLIPS: Clip[] = [
  { id: "covid-field",  durationS: 10, description: "Field workers in full PPE during a COVID-19 response operation." },
  { id: "liberia-labs", durationS: 4,  description: "U.S. military standing up biocontainment labs during the 2014 Liberia Ebola response." },
  { id: "cdc-donning",  durationS: 5,  description: "CDC Ebola training — donning Level-A PPE." },
  { id: "cdc-buddy",    durationS: 11, description: "CDC Ebola training — buddy-team patient simulation." },
  { id: "cdc-doffing",  durationS: 8,  description: "CDC Ebola training — controlled doffing under supervision." },
];

const POSTER = "/hero/poster.jpg";
const FADE_MS = 1_400;
// How much headroom to leave before a clip's natural EOF so rotation
// always fires before native `loop` wraps to t=0. ~300ms covers
// timeupdate cadence variance comfortably.
const SAFETY_MS = 300;
// Floor — never display a clip for less than this, even if its file
// is very short.
const MIN_DISPLAY_MS = 3_000;

const displayMsFor = (clip: Clip) =>
  Math.max(clip.durationS * 1000 - SAFETY_MS, MIN_DISPLAY_MS);

const srcFor = (id: string) => `/hero/${id}.mp4`;

// Atmospheric treatment: desaturate + cool tint so footage ties into the
// ink/inv palette rather than reading as literal documentary.
const TREATMENT =
  "grayscale(0.7) contrast(1.05) brightness(0.78) hue-rotate(190deg)";

function ClipVideo({ clip, isActive }: { clip: Clip; isActive: boolean }) {
  const videoRef = useRef<HTMLVideoElement | null>(null);

  // Re-base every visible turn at t=0. The neighbor element pre-mounts
  // with opacity:0 and autoPlay running, so by the time it becomes
  // active its currentTime is already mid-stream (or has wrapped). Without
  // this seek the user sees clips start from a random offset and
  // double-loop within their display turn.
  useEffect(() => {
    if (!isActive) return;
    const v = videoRef.current;
    if (!v) return;
    if (v.currentTime > 0.25) v.currentTime = 0;
    if (v.paused) v.play().catch(() => {});
  }, [isActive]);

  return (
    <video
      ref={videoRef}
      src={srcFor(clip.id)}
      poster={POSTER}
      autoPlay
      muted
      loop
      playsInline
      preload="auto"
      aria-label={clip.description}
      className="absolute inset-0 h-full w-full object-cover"
      style={{
        opacity: isActive ? 1 : 0,
        transition: `opacity ${FADE_MS}ms var(--ease-nt)`,
        filter: TREATMENT,
        transform: "scale(1.06)",
      }}
    />
  );
}

export type Scene1FieldProps = {
  /** Whether this scene is the active one (controls the rotation timer). */
  active: boolean;
};

export function Scene1Field({ active }: Scene1FieldProps) {
  const [idx, setIdx] = useState(0);
  const reduce = useReducedMotion();

  // Per-clip rotation: schedule the next cut based on the CURRENT clip's
  // actual file duration (see `displayMsFor`). A single fixed interval
  // doesn't work because durations range from 4s (liberia) to 11s (cdc-
  // buddy) — anything below the interval native-loops mid-display, and
  // anything above gets cut short. The `idx` dependency reschedules on
  // every advance, giving each clip its own dwell time.
  useEffect(() => {
    if (!active || reduce) return;
    const t = setTimeout(
      () => setIdx((i) => (i + 1) % CLIPS.length),
      displayMsFor(CLIPS[idx]),
    );
    return () => clearTimeout(t);
  }, [active, reduce, idx]);

  return (
    <div className="absolute inset-0 overflow-hidden bg-[var(--color-bg-ink)]">
      {/* Poster backdrop — instant first paint, and a graceful fallback
          if the clips haven't been generated yet. Treated to match. */}
      <div
        aria-hidden
        className="absolute inset-0 bg-cover bg-center"
        style={{
          backgroundImage: `url(${POSTER})`,
          filter: TREATMENT,
          transform: "scale(1.06)",
        }}
      />

      {/* Stacked video layers — render only the current and next clip so
          the decoder count stays low. Reduced-motion users keep the
          poster only. */}
      {!reduce &&
        CLIPS.map((clip, i) => {
          const isActive = i === idx;
          const isNeighbor = i === (idx + 1) % CLIPS.length;
          if (!isActive && !isNeighbor) return null;
          return <ClipVideo key={clip.id} clip={clip} isActive={isActive} />;
        })}

      {/* Cool overlay tint + dark vignette under the headline. */}
      <div
        aria-hidden
        className="absolute inset-0"
        style={{
          background:
            "linear-gradient(180deg, rgba(33,35,38,0.55) 0%, rgba(33,35,38,0.40) 40%, rgba(33,35,38,0.70) 100%)",
        }}
      />
      <div
        aria-hidden
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse at 25% 60%, rgba(33,35,38,0.55) 0%, rgba(33,35,38,0) 60%)",
        }}
      />
    </div>
  );
}
