"use client";

// Clips + poster live in public/hero/ and are generated by
// `npm run build:hero-clips`; ids here must match SOURCES in that script.

import { useEffect, useRef, useState } from "react";
import { useReducedMotion } from "@/lib/hooks";

type Clip = {
  id: string;
  description: string;
  /** Must match the trimmed window in scripts/build-hero-clips.mjs. */
  durationS: number;
};

const CLIPS: Clip[] = [
  { id: "covid-field",  durationS: 10, description: "Field workers in full PPE during a COVID-19 response operation." },
  { id: "cdc-donning",  durationS: 5,  description: "CDC Ebola training — donning Level-A PPE." },
  { id: "cdc-buddy",    durationS: 11, description: "CDC Ebola training — buddy-team patient simulation." },
  { id: "cdc-doffing",  durationS: 8,  description: "CDC Ebola training — controlled doffing under supervision." },
];

const POSTER = "/hero/poster.jpg";
const FADE_MS = 1_400;
// Headroom before a clip's EOF so rotation fires before `loop` wraps to t=0.
const SAFETY_MS = 300;
const MIN_DISPLAY_MS = 3_000;

const displayMsFor = (clip: Clip) =>
  Math.max(clip.durationS * 1000 - SAFETY_MS, MIN_DISPLAY_MS);

const srcFor = (id: string) => `/hero/${id}.mp4`;

const TREATMENT =
  "grayscale(0.7) contrast(1.05) brightness(0.78) hue-rotate(190deg)";

function ClipVideo({ clip, isActive }: { clip: Clip; isActive: boolean }) {
  const videoRef = useRef<HTMLVideoElement | null>(null);

  // The neighbour pre-mounts with autoPlay running, so it is already
  // mid-stream by its turn; re-base to t=0 or it starts at a random offset.
  useEffect(() => {
    if (!isActive) return;
    const v = videoRef.current;
    if (!v) return;
    if (v.currentTime > 0.25) v.currentTime = 0;
    if (v.paused) v.play().catch(() => {});
  }, [isActive]);

  return (
    <video
      ref={videoRef}
      src={srcFor(clip.id)}
      poster={POSTER}
      autoPlay
      muted
      loop
      playsInline
      preload="auto"
      aria-label={clip.description}
      className="absolute inset-0 h-full w-full object-cover"
      style={{
        opacity: isActive ? 1 : 0,
        transition: `opacity ${FADE_MS}ms var(--ease-nt)`,
        filter: TREATMENT,
        transform: "scale(1.06)",
      }}
    />
  );
}

export type Scene1FieldProps = {
  active: boolean;
};

export function Scene1Field({ active }: Scene1FieldProps) {
  const [idx, setIdx] = useState(0);
  const reduce = useReducedMotion();

  // A fixed interval can't work: clip durations differ, so each cut is
  // scheduled off the current clip's own duration (the `idx` dependency).
  useEffect(() => {
    if (!active || reduce) return;
    const t = setTimeout(
      () => setIdx((i) => (i + 1) % CLIPS.length),
      displayMsFor(CLIPS[idx]),
    );
    return () => clearTimeout(t);
  }, [active, reduce, idx]);

  return (
    <div className="absolute inset-0 overflow-hidden bg-[var(--color-bg-ink)]">
      <div
        aria-hidden
        className="absolute inset-0 bg-cover bg-center"
        style={{
          backgroundImage: `url(${POSTER})`,
          filter: TREATMENT,
          transform: "scale(1.06)",
        }}
      />

      {/* Only the current and next clip mount, to keep decoder count low. */}
      {!reduce &&
        CLIPS.map((clip, i) => {
          const isActive = i === idx;
          const isNeighbor = i === (idx + 1) % CLIPS.length;
          if (!isActive && !isNeighbor) return null;
          return <ClipVideo key={clip.id} clip={clip} isActive={isActive} />;
        })}

      <div
        aria-hidden
        className="absolute inset-0"
        style={{
          background:
            "linear-gradient(180deg, rgba(33,35,38,0.55) 0%, rgba(33,35,38,0.40) 40%, rgba(33,35,38,0.70) 100%)",
        }}
      />
      <div
        aria-hidden
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse at 25% 60%, rgba(33,35,38,0.55) 0%, rgba(33,35,38,0) 60%)",
        }}
      />
    </div>
  );
}
